import { Roboto_Serif } from 'next/font/google'
import './globals.css'
import NavItems from '@/Components/Navbar/NavItems'
import FooterBar from '@/Components/Footer/FooterBar'





const robotoSerif = Roboto_Serif({ subsets: ['latin'],
display: 'swap', })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoSerif.className}>
       <NavItems />
        <main>
        {children}
        </main>
        <FooterBar />
        </body>
    </html>
  )
}
